# Configuration file to run the DLC/Anipose pipeline
videos_path = 'Z:\NehaSapkal_new\Ball_system_data\bpn_project_pc1\11-12-2025\folders_to_Share\revision_6_30_2026\dummy_test'
common_files = "common_files"

# Pipeline settings
save_final_csv = false # if true, then the pipeline will also save the final preprocessed CSV file, useful if they need to be examined

# Only change defaults for development purposes
skip_preprocessing_functions = false
logging_level = "info" # debug, info, warning, error, critical

